### ISSUE TITLE
Remove gender recognition example

### ISSUE THREAD

**Issue by Ironholds** [IBM/AIF360#101]
Automated Gender Recognition has [been thoroughly shown](https://nbviewer.jupyter.org/github/IBM/AIF360/blob/master/examples/tutorial_gender_classification.ipynb) to be fundamentally discriminatory against trans people. Given that, it's somewhat bizzarre to see a tutorial in [how to make it "fairer"](https://nbviewer.jupyter.org/github/IBM/AIF360/blob/master/examples/tutorial_gender_classification.ipynb) in a project aiming to reduce discriminatory outcomes from ML. I would really suggest (and appreciate it!) if the example was removed - it has no place here.

**Comment by kvarsh** [comment]
Dear Mx. Keyes,

Thank you for raising this important concern.  As you rightly point out, the task itself is fundamentally problematic. Even if there may not have been maleficent intentions when the tutorial was composed, I agree that it should be taken down going forward.  We will do so posthaste.

**Comment by Ironholds** [comment]
Thanks!

**Comment by autoih** [comment]
Hi @pronics2004, should this issue be closed?

**Comment by pronics2004** [comment]
yes. thanks!
