### ISSUE TITLE
Statistical_parity/disparate impact results without prediction?

### ISSUE THREAD

**Issue by StevenZindel** [IBM/AIF360#108]
Dear IBM,

How is it possible to get results for the metrics in the title (among other) without providing any prediction?

**Comment by StevenZindel** [comment]
Aah oke I missed that the metrics always run on the labels..

If I may suggest: I find it very strange to update/change the label feature with the actual prediction.. You see this also when doing: fit_predict with a postprocessing algorithm where you have to pass two datasets.. which are completely the same besides the label attribute.. Would be ideal if a prediction attribute exists which is used instead of updating the label attrbute.

**Comment by hoffmansc** [comment]
Yes, there were many design choices we considered for this. The reason we chose to separate input datasets and output datasets is one may wish to compare metrics at different stages of the pipeline which would not be possible if the dataset were modified in-place (e.g. in preprocessing, the features may change). In most cases, the underlying data should not be copied unless it differs between input and output.
