### ISSUE TITLE
Missing dependencies: ModuleNotFoundError: No module named 'numba'

### ISSUE THREAD

**Issue by bottydim** [IBM/AIF360#119]
`from aif360.datasets import GermanDataset`
`from aif360.metrics import BinaryLabelDatasetMetric`
`from aif360.algorithms.preprocessing import Reweighing`

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-11-8c39b9f7a866> in <module>
>       1 from aif360.datasets import GermanDataset
>       2 from aif360.metrics import BinaryLabelDatasetMetric
> ----> 3 from aif360.algorithms.preprocessing import Reweighing
> 
> ~/.local/lib/python3.6/site-packages/aif360/algorithms/preprocessing/__init__.py in <module>
>       1 from aif360.algorithms.preprocessing.disparate_impact_remover import DisparateImpactRemover
> ----> 2 from aif360.algorithms.preprocessing.lfr import LFR
>       3 from aif360.algorithms.preprocessing.optim_preproc import OptimPreproc
>       4 from aif360.algorithms.preprocessing.reweighing import Reweighing
> 
> ~/.local/lib/python3.6/site-packages/aif360/algorithms/preprocessing/lfr.py in <module>
>       3 
>       4 from aif360.algorithms import Transformer
> ----> 5 from aif360.algorithms.preprocessing.lfr_helpers import helpers as lfr_helpers
>       6 
>       7 
> 
> ~/.local/lib/python3.6/site-packages/aif360/algorithms/preprocessing/lfr_helpers/helpers.py in <module>
>       1 # Based on code from https://github.com/zjelveh/learning-fair-representations
> ----> 2 from numba.decorators import jit
>       3 import numpy as np
>       4 
>       5 @jit
> 
> ModuleNotFoundError: No module named 'numba'

**Comment by hoffmansc** [comment]
Hi! Is this after installing the requirements.txt?

**Comment by bottydim** [comment]
Hi :) Sorry, there was a fine print: 

> Some algorithms require additional dependencies not included in the minimal installation. To use these, we recommend a full installation.
> 

You might find it useful from a user perspective to have all libraries, required by the core code, included within the pip install setup.

**Comment by DEHO-OSCAR-BLESSED** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-b9e5bc932b87> in <module>
      8 from aif360.datasets import GermanDataset
      9 from aif360.metrics import BinaryLabelDatasetMetric
---> 10 from aif360.algorithms.preprocessing import Reweighing
     11 
     12 from IPython.display import Markdown, display

~\AppData\Local\Programs\Python\Python37\lib\site-packages\aif360\algorithms\preprocessing\__init__.py in <module>
      1 from aif360.algorithms.preprocessing.disparate_impact_remover import DisparateImpactRemover
----> 2 from aif360.algorithms.preprocessing.lfr import LFR
      3 from aif360.algorithms.preprocessing.optim_preproc import OptimPreproc
      4 from aif360.algorithms.preprocessing.reweighing import Reweighing

~\AppData\Local\Programs\Python\Python37\lib\site-packages\aif360\algorithms\preprocessing\lfr.py in <module>
      3 
      4 from aif360.algorithms import Transformer
----> 5 from aif360.algorithms.preprocessing.lfr_helpers import helpers as lfr_helpers
      6 
      7 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\aif360\algorithms\preprocessing\lfr_helpers\helpers.py in <module>
      1 # Based on code from https://github.com/zjelveh/learning-fair-representations
----> 2 from numba.decorators import jit
      3 import numpy as np
      4 
      5 @jit

ModuleNotFoundError: No module named 'numba'

Facing the same problem... anyway to fix it??

**Comment by hildeweerts** [comment]
I ran into the same "issue" today. Although it can be easily fixed by running ```pip install numba```, it feels like running the first block of code from the introduction tutorial should not require installing additional libraries. Like @bottydim, I would recommend putting numba in the setup.
