### ISSUE TITLE
Documentation Typo for average_odds_difference()

### ISSUE THREAD

**Issue by bottydim** [IBM/AIF360#126]
Hi AIF360 team,

Thank you for the excellent repo & superb documentation! 

I believe there is a typo for both:
https://aif360.readthedocs.io/en/latest/modules/metrics.html#aif360.metrics.ClassificationMetric.average_odds_difference

https://aif360.readthedocs.io/en/latest/modules/metrics.html#aif360.metrics.ClassificationMetric.average_abs_odds_difference

The implementation correctly returns 

1/2[(FPRD=unprivileged−FPRD=privileged)+(TPRD=**unprivileged** - TPRD=**privileged**))]

vs the stated

1/2[(FPRD=unprivileged−FPRD=privileged)+(TPRD=**privileged** - TPRD=**unprivileged**))]

**Comment by hoffmansc** [comment]
It looks like the docstring is fixed in the code but readthedocs is showing an older version for some reason. I'll investigate.

**Comment by hoffmansc** [comment]
Should be fixed on readthedocs now. Thanks for pointing it out!
