### ISSUE TITLE
The german credit dataset's privileged class should be Age > 25, not Age >= 25

### ISSUE THREAD

**Issue by zywind** [IBM/AIF360#128]
https://github.com/IBM/AIF360/blob/c718f1d6cd11f1a7536a1317ea280abd961a7c79/aif360/datasets/german_dataset.py#L31

So I looked at the original paper on this dataset: F. Kamiran and T. Calders, “Classifying without discriminating,” They mentioned that 190 account holders were classified as young. This corresponds to classifying people <= 25 as Young. If set as < 25, it would remove about 50 instances from the Young group. This might be why the results on this dataset was unstable. Changing this should also improve the results on the website.

**Comment by krvarshney** [comment]
really interesting
