### ISSUE TITLE
Subset of Dataset

### ISSUE THREAD

**Issue by bhavyaghai** [IBM/AIF360#136]
I want to train in-processing algorithms like Prejudice Remover, ART classifier, etc. using a specific subset of dataset like Adult Income, etc. Is there a way to create a subset based on row numbers like df.loc[[2,3,4,5]]?
If so, I can then train and predict using the existing api which take 'dataset' type as input for fit & predict function respectively. 
Not sure if this functionality is supported out of the box or if there is some workaround?

**Comment by nrkarthikeyan** [comment]
Hi @bhavyaghai , there is no method currently to do this. But it should be easy to implement. Basically, we have to create a new dataset by subsetting the fields features, labels, scores, protected_attributes, instance_names and instance_weights from the original dataset.  The rest of the fields can be just copied over. We may have to change the metadata also to denote the subsetting.

**Comment by bhavyaghai** [comment]
Can you give me any timeframe on when can I expect this feature?
My current research is dependent on this feature.

**Comment by krvarshney** [comment]
@bhavyaghai, please feel free to implement it yourself and contribute it to the community.  I am sure many people will benefit from it.

**Comment by bhavyaghai** [comment]
@krvarshney @nrkarthikeyan Thanks for your support!
I have added a pull request where I have implemented the subset feature.
It seems to work fine on my end.
Hope it helps!
