### ISSUE TITLE
Slack channel link broken

### ISSUE THREAD

**Issue by maxjeblick** [IBM/AIF360#156]
The invitation link to the slack channel is currently broken.

**Comment by michaelhind** [comment]
Thanks for letting us know.   As a security measure, the link expires periodically.  We will update the link on the website shortly.  In the meantime, here is the new link to subscribe

https://join.slack.com/t/aif360/shared_invite/zt-5hfvuafo-X0~g6tgJQ~7tIAT~S294TQ

**Comment by michaelhind** [comment]
This is now fixed.  Thanks!
