### ISSUE TITLE
GerryFairClassifier Pre and Postprocessing Equivalent

### ISSUE THREAD

**Issue by firmai** [IBM/AIF360#160]
Is there pre and post-processing techniques available with respect to rich subgroup fairness. And is there any studies comparing model-agnostic methods with model-specific methods? I just can't imagine none existing, I have looked everywhere. Thanks.

**Comment by hoffmansc** [comment]
Regarding the first question, we only have an in-processing algorithm available for rich subgroup fairness.

As for the second question, there are a few comparison papers. For example, this one from [fairness-comparison](https://arxiv.org/pdf/1802.04422.pdf). [Our paper](https://arxiv.org/pdf/1810.01943.pdf) also contains some results comparing the algorithms we have in AIF360.

You might have more luck with general informational questions by posting in our [Slack](https://aif360.slack.com/).
