### ISSUE TITLE
Missing dependencies from setup.py

### ISSUE THREAD

**Issue by ankushjain2001** [IBM/AIF360#169]
If one does a simple pip install aif360, the DIRemover intervention and the AdversarialDebiasing model won't work straight out of the box. This is due to their missing dependencies, namely, BlackBoxAuditing and Tensorflow.

I noticed that the requirements.txt has these dependencies and it is used in Travis tests but not in setup.py. Tensorflow is a particularly tricky installation because by default tf2 is installed through pip and one is forced to find the correct tensorflow version for AIF360 manually.

Is this intentional for some reason?

**Comment by hoffmansc** [comment]
Yes, this is intentional. A couple dependencies (mainly cvxpy) can be very tricky to install, especially on Windows. To lower the barrier to entry, we made these "extra" dependencies optional.

With the latest release, you can install everything in one line:
```sh
pip install 'aif360[all]>=0.3.0rc0'
```
