### ISSUE TITLE
PrejudiceRemover returns same result when trying with different eta

### ISSUE THREAD

**Issue by ellennugroho** [IBM/AIF360#172]
Hi, I've been exploring your library for one of my projects. When I was experimenting on using Prejudice Remover algorithm on Adult dataset, it will return same results no matter what the eta is. However, it works fine when I used different datasets such as COMPAS and German Credit Score -- the results differ with different etas. Can you help me to understand why is it happening? Thanks a lot!

For Adult Dataset, I used your `load_preproc_data_adult`.
I tested on `etas = [1,15,50,100]` iteratively, and I tested on `sensitive_attr='race'` and `sensitive_attr='sex'`. Both are giving me same results no matter what the eta is.

**Comment by monindersingh** [comment]
Hi, The code for Prejudice Remover is the original (Kamishima's) code with a wrapper around it. However, I will take a look to make sure nothing untoward is happening. Can you please provide your code using the Adult dataset?

**Comment by ellennugroho** [comment]
Thank you for following up. Here's my code:

```python
from aif360.datasets import AdultDataset
from aif360.algorithms.preprocessing.optim_preproc_helpers.data_preproc_functions import load_preproc_data_adult
from aif360.metrics import BinaryLabelDatasetMetric, ClassificationMetric
from aif360.algorithms.inprocessing.prejudice_remover import PrejudiceRemover

from sklearn.metrics import accuracy_score

dataset_orig = load_preproc_data_adult()

privileged_groups = [{'race': 1}]
unprivileged_groups = [{'race': 0}]

dataset_orig_train, dataset_orig_test = dataset_orig.split([0.7], shuffle=True)

etas = [1,15,50,100]

for eta in etas:
    debiased_model = PrejudiceRemover(eta=eta, sensitive_attr='race', class_attr=dataset_orig_train.label_names[0])        
    model = debiased_model.fit(dataset_orig_train)
    pred = model.predict(dataset_orig_test)

    metric = ClassificationMetric(dataset_orig_test, pred, unprivileged_groups=unprivileged_groups, privileged_groups=privileged_groups)

    print('Accuracy:', accuracy_score(pred.labels, dataset_orig_test.labels))
    print('Disparity impact:', metric.disparate_impact())
    print("Statistical Parity Difference = %f" % metric.statistical_parity_difference())
    print("Equal opportunity difference = %f" % metric.equal_opportunity_difference())
    print("Average odds difference = %f" % metric.average_odds_difference())
    print("Theil_index = %f" % metric.theil_index())
    print()
```

and here's my results when running it:
```
Accuracy: 0.7908960622398143
Disparity impact: 0.3745778126422821
Statistical Parity Difference = -0.124567
Equal opportunity difference = -0.198108
Average odds difference = -0.133181
Theil_index = 0.172030

Accuracy: 0.7908960622398143
Disparity impact: 0.3745778126422821
Statistical Parity Difference = -0.124567
Equal opportunity difference = -0.198108
Average odds difference = -0.133181
Theil_index = 0.172030

Accuracy: 0.7908960622398143
Disparity impact: 0.3745778126422821
Statistical Parity Difference = -0.124567
Equal opportunity difference = -0.198108
Average odds difference = -0.133181
Theil_index = 0.172030

Accuracy: 0.7908960622398143
Disparity impact: 0.3745778126422821
Statistical Parity Difference = -0.124567
Equal opportunity difference = -0.198108
Average odds difference = -0.133181
Theil_index = 0.172030
```

**Comment by monindersingh** [comment]
Hi
I think the results you are getting are an artifact of the dataset itself. The Adult dataset that is produced by load_preproc_data_adult() has only two discretized features (plus the sensitive features). I suspect eta has a minimal impact on the model and so PR is probably not a good model for it.
If you use the full Adult dataset (using dataset_orig = AdultDataset()), you will see that eta has an effect on fairness pretty quickly. Be sure to scale the features since PR uses regularized LR.
For example,
scaler = StandardScaler()
dataset_orig_train.features = scaler.fit_transform(dataset_orig_train.features)
dataset_orig_test.features = scaler.transform(dataset_orig_test.features)
...

**Comment by ellennugroho** [comment]
I see. Thank you very much for the explanation! I'm closing this issue.
