### ISSUE TITLE
LFR seems to make the data more unfair

### ISSUE THREAD

**Issue by Angelina-Wang** [IBM/AIF360#173]
In demo_lfr.ipynb, the transformed dataset seems to be making it more unfair rather than more fair? The difference in mean outcomes starts out as -.196576, but then after the transformation into a supposedly more fair representation, this difference gets larger at all thresholds. Perhaps there’s a bug in the LFR code?

**Comment by pronics2004** [comment]
In the LFR demo notebook is demonstrating LFR as a preprocessing algorithm and geared towards improving `consistency` a measure of individual fairness. 

The following default parameters can be tuned to improve other metrics.
```
k (int, optional): Number of prototypes.
Ax (float, optional): Input reconstruction quality term weight.
Az (float, optional): Fairness constraint term weight.
Ay (float, optional): Output prediction error
```

For usage questions, please reach out to the slack channel.

Feel free to reopen the issue or create a new issue if you find any bugs in the implementation.
