### ISSUE TITLE
make_scorer on sklearn metrics.py wrong attribute

### ISSUE THREAD

**Issue by motapaolla** [IBM/AIF360#177]
The `make_scorer` from `aif360/sklearn/metrics/metrics.py` file has the attribute `ratio` which I think it should be `is_ratio` instead since if the attribute is `ratio` it will always be True.

**Comment by hoffmansc** [comment]
Could you make a PR to the master branch with this change? Thanks!

**Comment by motapaolla** [comment]
Sure
