### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.decorators'

### ISSUE THREAD

**Issue by kiran-kate** [IBM/AIF360#185]
There is `from numba.decorators import jit` in `aif360/algorithms/preprocessing/lfr_helpers/helpers.py` which fails with 
`ModuleNotFoundError: No module named 'numba.decorators'`. Seems like numba released a new version on June 11th, which may have caused this. Pinning the version in setup.py may solve it, at least for now.

**Comment by SSaishruthi** [comment]
@hoffmansc I faced the same issue.

Either we need to pin this to 0.48.0 or update code to `numba.core.decorators`

**Comment by dvd-king** [comment]
@hoffmansc Getting the same error. 

!pip install numba==0.48
from numba.decorators import jit
import aif360.algorithms.preprocessing
from aif360.algorithms.preprocessing import Reweighing

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-3b650a37b035> in <module>
      1 #!pip install numba==0.48
----> 2 from numba.decorators import jit
      3 import aif360.algorithms.preprocessing
      4 from aif360.algorithms.preprocessing import Reweighing

ModuleNotFoundError: No module named 'numba.decorators'

**Comment by hoffmansc** [comment]
@dvd-king what version of AIF360 are you using? Are you able to upgrade to the latest version, v0.4.0? That removes the numba dependency entirely.
