### ISSUE TITLE
Error getting UCI Adult dataset

### ISSUE THREAD

**Issue by michaelhind** [IBM/AIF360#34]
The Travis build is failing due to the ftp to grab the UCI adult dataset not working.  Details here:  https://travis-ci.com/IBM/AIF360/jobs/150380518   I tried the failing wget command from a local cgywin shell on my laptop and it worked for me, so the problem doesn't seem to be on the UCI side.

**Comment by hoffmansc** [comment]
Fixed for now (#33). Travis will now look at the https URL for the datasets first and fall back to ftp if necessary.
