### ISSUE TITLE
Python 3.6 failing

### ISSUE THREAD

**Issue by michaelhind** [IBM/AIF360#35]
The latest PR failed for python 3.6 (but passed for 2.7).  Here's the details: https://travis-ci.com/IBM/AIF360/jobs/151221128

**Comment by nrkarthikeyan** [comment]
Seems like it passed after i restarted the build.

**Comment by hoffmansc** [comment]
#37 fixes this

**Comment by hoffmansc** [comment]
#37 did not fix this...

**Comment by michaelhind** [comment]
Looks like merge of issue #40 fixed this.
