### ISSUE TITLE
features_to_drop in Class  MEPSDataset19 not working

### ISSUE THREAD

**Issue by sainyam** [IBM/AIF360#43]
I tried to run the MEPSDataset19 example with features_to_drop. It ran with some features but not with some eg. 'PHQ242'

Error it gave: KeyError: "['PHQ242'] not in index"

Not sure if I did something wrong but found a workaround by not keeping it in features_to_keep so that the question to drop does not arise.

**Comment by monindersingh** [comment]
Hi
Can you please provide some more detail? The code you used, the line where the error occurred, etc...best will be if you attach the code. I suspect this is an issue with the datafile but need to verify.

**Comment by monindersingh** [comment]
Identified slight bug in code. Fixed and pull request created.
