### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by biosopher** [IBM/AIF360#44]
What OS was AIF360 built on?  I'm attempting to run on a Macbook Pro with the latest Mac OS however I am getting errors when attempting to install the module 'cvxpy'.  During the 'pip install cvxpy', I get numerous compilation errors:

```
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from cvxpy/cvxcore/src/cvxcore.cpp:15:
  cvxpy/cvxcore/src/cvxcore.hpp:18:10: fatal error: 'vector' file not found
  #include <vector>
           ^~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cvxpy
```

**Comment by biosopher** [comment]
Getting closer.  Found first part of a solution here: https://www.cvxpy.org/install/index.html
Switched from "pip install cvxgrp" to this:
```
conda install -c conda-forge lapack
conda install -c cvxgrp cvxpy
```

So now cvxgrp is installed but getting this error:
```
/anaconda/envs/dlaas_cos/lib/python3.6/site-packages/aif360/algorithms/preprocessing/optim_preproc_helpers/opt_tools.py in <module>()
     15 import numpy as np
     16 import pandas as pd
---> 17 from cvxpy import Problem, Minimize, Variable, sum_entries,\
     18                   mul_elemwise, norm
     19 from logging import info, debug, warn

ImportError: cannot import name 'sum_entries'
```

**Comment by biosopher** [comment]
What version of CVXPY is used by AIF360?  According to the current v0.4.8 release of CVXPY:
```
Several CVXPY atoms have been renamed: ...sum_entries is now sum...Due to the name changes, we now strongly recommend against importing CVXPY using the syntax from cvxpy import *.
```
https://media.readthedocs.org/pdf/cvxpy/stable/cvxpy.pdf

**Comment by hoffmansc** [comment]
Hi! It looks like your most recent error is due to a newer version of cvxpy. We require 0.4.11. Are you using a virtual python environment to install packages?

**Comment by biosopher** [comment]
Yes.  I'm using conda and used this command. I expect that should have installed the most recent release.
```
conda install -c cvxgrp cvxpy
```
As above though, are you sure you're using v0.4.11?  The PDF above says that `sum_entries` was rename to `sum` in v0.4.8 and also recommends not using `from cvxpy import *`.

**Comment by biosopher** [comment]
And I'm guessing that since v0.4.8 was installed by `conda install -c cvxgrp cvxpy` then v0.4.11 isn't yet available via conda install?

**Comment by hoffmansc** [comment]
Sorry, I wasn't clear. I meant did you create a new environment like `conda create --name aif360 python=3.6`.

The latest version of cvxpy is incompatible with our code as you pointed out. It appears that 0.4.11 is not available on conda though. You could try a lower version but we've only tested with 0.4.11. It should be available from through pip though: `pip install cvxpy==0.4.11`

If you still encounter the gcc error you can try `conda install -c cvxgrp libgcc`

**Comment by hoffmansc** [comment]
Actually, the original error may have occurred if you haven't installed the command line tools on that machine before. You can do this by `xcode-select --install`. This should give you things like gcc, etc.

**Comment by biosopher** [comment]
Starting over again with a fresh environment and these commands:
```
$xcode-select --install
$conda install -c cvxgrp libgcc
```
This seems to have worked slightly better.  Now getting this error:
```
...
In file included from /usr/local/include/stdint.h:59:
    In file included from /usr/local/include/stdint.h:59:
    In file included from /usr/local/include/stdint.h:59:
    In file included from /usr/local/include/stdint.h:59:
    In file included from /usr/local/include/stdint.h:59:
    /usr/local/include/stdint.h:2:10: error: #include nested too deeply
    #include <stddef.h>
             ^
    /usr/local/include/stdint.h:59:11: error: #include nested too deeply
    # include <stdint.h>
              ^
    /usr/local/include/stdint.h:72:11: error: #include nested too deeply
    # include <sys/types.h>
              ^
    /usr/local/include/stdint.h:76:10: error: #include nested too deeply
    #include <limits.h>
             ^
    /usr/local/include/stdint.h:82:11: error: #include nested too deeply
    # include <inttypes.h>
              ^
    5 errors generated.
    error: command 'gcc' failed with exit status 
```
Any ideas?  Can't find any guidance/workarounds in Google.

**Comment by biosopher** [comment]
Also looks like v0.4.* is 2.5 years old.  Seems easiest for all users if AIF360 is updated to the latest version as my guess is most people will hit the same issues as me.
https://pypi.org/project/cvxpy/#history

**Comment by hoffmansc** [comment]
That's odd. Which command caused that error? I don't have that header file on my machine so it might have been installed by something else. According to https://github.com/SOHU-Co/kafka-node/issues/881, you might have luck just renaming it.

Also, when I installed on a mac, I was able to do `pip install cvxpy==0.4.11` with just the xcode gcc installed. I didn't need to install libgcc from cvxgrp.

**Comment by biosopher** [comment]
OK.  Starting over again and just editing the AIF360 file to use the latest version of cvxpy.  Just ran this:
```
$conda create --name aios python=3.6
$source activate aios
$conda install -c cvxgrp cvxpy
```
Then I edited the opt_tools.py from this:
```
from cvxpy import Problem, Minimize, Variable, sum_entries, mul_elemwise, norm
```
to this
```
from cvxpy import Problem, Minimize, Variable, norm
import cvxpy as cvx
```
and replaced `sum_entries` to `cvx.sum` and `mul_elemwise` to `cvx.multiply`

**Comment by biosopher** [comment]
OK, finally found the solution.  Conda had the older v0.4.9 version of cvxpy so installed it as below and the notebook now works:
```
$conda create --name aios python=3.6
$source activate aios
$conda install -c cvxgrp cvxpy=0.4.9
```
