### ISSUE TITLE
Typo in the German Credit Scoring tutorial

### ISSUE THREAD

**Issue by biosopher** [IBM/AIF360#45]
In step 5 of the Credit Scoring notebook, there is a typo in the section below.  The decimal place is shifted 1 to the left in this text above the cell: `the difference in mean outcomes is now 0.18250.`  The value should instead by `0.018250` as shown below the cell.

![image](https://user-images.githubusercontent.com/814855/48246452-59785480-e3a4-11e8-9b71-a2a2fd35f848.png)

**Comment by michaelhind** [comment]
Fixed with pull request #46
