### ISSUE TITLE
Executing the Credit Risk notebook does not generate a de-biased dataset

### ISSUE THREAD

**Issue by biosopher** [IBM/AIF360#51]
Executing the [Credit Risk Notebook](https://github.com/IBM/AIF360/blob/master/examples/tutorial_credit_scoring.ipynb) does not generate a de-biased dataset.  The results below are from a brand now GIT pull from the AIF360 repo.  As shown at the end, the new "debiased" model now over twice as biased as the original model:

![image](https://user-images.githubusercontent.com/814855/48462282-6b833a00-e78c-11e8-9218-3d351838a46e.png)
![image](https://user-images.githubusercontent.com/814855/48462288-72aa4800-e78c-11e8-92f5-703a566cded4.png)
![image](https://user-images.githubusercontent.com/814855/48462303-78079280-e78c-11e8-9e59-7ff9e04233c9.png)

**Comment by adrinjalali** [comment]
I [almost] concur. I get 0.11 vs 0.21. Is the input data changing? What's the source of these different results?

It may be a good idea to have some of these as tests or doctests in the docstrings (as examples).

**Comment by biosopher** [comment]
@nrkarthikeyan Can you advise on this?  Just sent an email cc'ing the AIOS team.  Need this fixed so we can show integration.

**Comment by biosopher** [comment]
I know the German credit risk dataset is small, but that doesn't explain the odd behavior of AIF360's notebook.  E.g. I looped through a hundred different splits of that dataset looking for one that would de-bias properly.  

In the process I found that for EVERY split of test/train, AIF360 actually generates a more biased dataset than the initial one.  Something else is wrong here.

Here's my notebook showing this bug: 
[tutorial_credit_scoring_merged.ipynb.zip](https://github.com/IBM/AIF360/files/2614414/tutorial_credit_scoring_merged.ipynb.zip)

**Comment by adrinjalali** [comment]
The warning shown in the notebook might also be significant. The preprocessing sets the privileged and unprivileged groups, (gender and race I guess), and then in the notebook when the user tries to set the privileged/unprivileged group, it's ignored as a result. That would quite change the results.

**Comment by nrkarthikeyan** [comment]
Hi all, the optimized pre-processing (used in the original credit scoring tutorial) has a lot of randomness built into it, which will create issues with small datasets. I suggest that we use re-weighing pre-processing to circumvent this issue. Please see the attached notebook: 
[tutorial_credit_scoring_reweighing.ipynb.zip](https://github.com/IBM/AIF360/files/2615783/tutorial_credit_scoring_reweighing.ipynb.zip)

The key thing to keep in mind is that reweighing pre-processing works by changing the instance level weights (this is available in dataset.instance_weights). So, the classifier trained on the debiased data should be capable of handling instance level weights. Let me know what you folks think.

**Comment by michaelhind** [comment]
We just got a report from @mariaborbones that an underlying package (cvxpy) that the de-biased technique uses in this tutorial recently changed the semantics of their API.  Maria has submitted a pull request to fix the issue (https://github.com/IBM/AIF360/pull/59), which we are reviewing.

**Comment by hoffmansc** [comment]
Alternatively, we could run it on the Adult dataset which seems to be much more stable and effective.
[tutorial_credit_scoring_adult.ipynb.zip](https://github.com/IBM/AIF360/files/2649622/tutorial_credit_scoring_adult.ipynb.zip)

**Comment by scottdangelo** [comment]
Any update on fixing this? We've a [code pattern](https://github.com/IBM/ensure-loan-fairness-aif360) on developer.ibm.com that uses this notebook, and it shows that using AIF360 makes fairness worse.

**Comment by nrkarthikeyan** [comment]
We have modified the tutorial and this issue is fixed.
