### ISSUE TITLE
Possibly incorrect indentation of for loop

### ISSUE THREAD

**Issue by poojagupta1007** [IBM/AIF360#80]
The for loop in line 125 should be outside the else part. 
Otherwise for loop runs for the initializations done in else part but it should work with both, if and else initializations.

https://github.com/IBM/AIF360/blob/0cf736f0310075a244dc63a045dbc7636dda2f2c/aif360/algorithms/postprocessing/reject_option_classification.py#L116-L132

**Comment by hoffmansc** [comment]
Good catch! Looks like you're right, it's a typo. Thanks for pointing it out!

**Comment by poojagupta1007** [comment]
Thank You!!
