### ISSUE TITLE
base rate computation in Equalized odds post processing

### ISSUE THREAD

**Issue by nrkarthikeyan** [IBM/AIF360#87]
Base rates for the privileged and unprivileged groups are not correctly estimated in the code.

https://github.com/IBM/AIF360/blob/0cf736f0310075a244dc63a045dbc7636dda2f2c/aif360/algorithms/postprocessing/eq_odds_postprocessing.py#L93

**Comment by JohannesJacob** [comment]
Is the issue resolved? Not sure, if Kibnelson's code is the final solution. It implements the fairness constraint, but when using it on some test data the overall accuracy turns out to be very low.

Any help would be much appreciated. Thanks!
