### ISSUE TITLE
Unable to replicate demo_lfr.ipynb notebook

### ISSUE THREAD

**Issue by sumit-kothari** [IBM/AIF360#92]
Whilst trying to replicate [demo_lrf](https://github.com/IBM/AIF360/blob/master/examples/demo_lfr.ipynb) notebook, I am getting following error.
I also tried changes mentioned in [issue 83](https://github.com/IBM/AIF360/issues/83). 

    /AIF360/aif360/algorithms/preprocessing/lfr_helpers/helpers.py:62: NumbaWarning: 
    Compilation is falling back to object mode WITH looplifting enabled because Function "LFR_optim_obj" failed type inference due to: Unknown attribute 'iters' of type recursive(type(CPUDispatcher(<function LFR_optim_obj at 0x7f5fea38a2f0>)))

    File "AIF360/aif360/algorithms/preprocessing/lfr_helpers/helpers.py", line 66:
    def LFR_optim_obj(params, data_sensitive, data_nonsensitive, y_sensitive,
        <source elided>

        LFR_optim_obj.iters += 1
        ^

    [1] During: typing of get attribute at /AIF360/aif360/algorithms/preprocessing/lfr_helpers/helpers.py (66)

    File "AIF360/aif360/algorithms/preprocessing/lfr_helpers/helpers.py", line 66:
    def LFR_optim_obj(params, data_sensitive, data_nonsensitive, y_sensitive,
        <source elided>

        LFR_optim_obj.iters += 1
        ^

    @jit
    /AIF360/aif360/algorithms/preprocessing/lfr_helpers/helpers.py:62: NumbaWarning: 
    Compilation is falling back to object mode WITHOUT looplifting enabled because Function "LFR_optim_obj" failed type inference due to: cannot determine Numba type of <class 'numba.dispatcher.LiftedLoop'>

    File "AIF360/aif360/algorithms/preprocessing/lfr_helpers/helpers.py", line 85:
    def LFR_optim_obj(params, data_sensitive, data_nonsensitive, y_sensitive,
        <source elided>
        L_z = 0.0
        for j in range(k):
        ^

    @jit

**Comment by psattige** [comment]
This seems to be related to the numba version. Currently numba==0.42.0 is supported.

**Comment by sumit-kothari** [comment]
Yes, thanks that (numba==0.42.0) fixed it.
